function g = gaussC(x, y, sigma, center)
    % gaussC creates a 2D Gaussian centered at 'center' with standard deviation 'sigma'.
    % x and y are matrices generated by ndgrid.
    xc = center(1);
    yc = center(2);
    g = exp(-(((x - xc).^2 + (y - yc).^2) / (2 * sigma^2)));
end